ets-berkeley-edu/datacultures

- app/assets/stylesheets/_gallery.scss
- app/assets/templates/gallery_list.html
https://jira.ets.berkeley.edu/jira/browse/CYB-401
Add a "No results" message to the Gallery
> CYB-401 - Add a "No results" message to the Gallery

- app/assets/templates/engagement_index_list.html
- app/assets/templates/engagement_index_user_info.html
- app/assets/templates/gallery_item.html
- app/controllers/api/v1/engagement_index_controller.rb
The Engagement Index date sorting was not always working correctly (e.g. dates across different years)
https://jira.ets.berkeley.edu/jira/browse/CYB-404
> CYB-404 - Engagement Index date sorting is not working correctly

- app/assets/javascripts/angular/controllers/engagementIndexController.js
- app/assets/javascripts/angular/controllers/galleryController.js
- app/assets/stylesheets/_engagement_index.scss
- app/assets/stylesheets/_gallery.scss
- app/assets/stylesheets/_main.scss
- app/assets/stylesheets/_points_configuration.scss
- app/assets/templates/engagement_index.html
- app/assets/templates/engagement_index_landing.html
- app/assets/templates/engagement_index_list.html
- app/assets/templates/engagement_index_not_share.html
- app/assets/templates/engagement_index_sharing_option.html
- app/assets/templates/gallery.html
- app/assets/templates/gallery_item.html
- app/assets/templates/gallery_list.html
- app/assets/templates/points_configuration.html
- Styling improvements to give the various tools an overall better and more consistent look
- Improved the interactions around sharing your points on the engagement index
- Improved the engagement index instructions
https://jira.ets.berkeley.edu/jira/browse/CYB-371
https://jira.ets.berkeley.edu/jira/browse/CYB-399
https://jira.ets.berkeley.edu/jira/browse/CYB-387
> CYB-371 - User interface tweaks

- Gemfile
- app/assets/javascripts/angular/controllers/engagementIndexController.js
- app/assets/javascripts/angular/factories/engagementIndexFactory.js
- app/assets/javascripts/application.js
- app/assets/stylesheets/_engagement_index.scss
- app/assets/templates/engagement_index_list.html
- app/assets/templates/engagement_index_user_info.html
- config/locales/en.yml
Made the engagement index a bit more engaging by showing the rank in the engagement index leaderboard and showing the current user's rank, total number of points and a box plot showing how they rank in the class.
https://jira.ets.berkeley.edu/jira/browse/CYB-400
> CYB-400 - Present visually more appealing percentile information

- app/assets/javascripts/angular/services/utilService.js
iFrame resizing also needs to take place when the screen is resized
https://jira.ets.berkeley.edu/jira/browse/CYB-406
> CYB-406 - iFrame resizing also needs to take place when the screen is resized

- bin/deploy.sh
https://jira.ets.berkeley.edu/jira/browse/CYB-405
If Sidekiq is running (pid found) then sidekiqctl stop. Plus, new and improved 'ps' command to isolate only the pid id.
> CYB-405, auto-deploys get 'FAILED to stop Sidekiq, Process doesn't exist'

- app/assets/templates/engagement_index_landing.html
Engagement index: preview image could use an accessible description
https://jira.ets.berkeley.edu/jira/browse/CYB-410
> CYB-410 - Engagement index: preview image could use an accessible description

- app/assets/javascripts/angular/controllers/engagementIndexController.js
Engagement index: graph legend shows some values reversed
https://jira.ets.berkeley.edu/jira/browse/CYB-413
> CYB-413 - Engagement index: graph legend shows some values reversed

- app/assets/javascripts/angular/controllers/engagementIndexController.js
- app/assets/javascripts/angular/services/utilService.js
- app/assets/stylesheets/_engagement_index.scss
- app/assets/stylesheets/_main.scss
- Fixed popover on Safari 7
- Fixed an issue where the frame resizing wasn't quite working on Safari and Chrome
https://jira.ets.berkeley.edu/jira/browse/CYB-414
> CYB-414 - Engagement index: graph popover doesn't work on Safari

- app/assets/javascripts/angular/controllers/pointsConfigurationController.js
Added missing iFrame resize calls for the points configuration
https://jira.ets.berkeley.edu/jira/browse/CYB-415
> CYB-415 - Points config: on Firefox, removed activity vanishes during removal

- app/assets/javascripts/angular/services/utilService.js
Gallery: content will not fit within available iframe height
https://jira.ets.berkeley.edu/jira/browse/CYB-419
> CYB-419 - Gallery: content will not fit within available iframe height

- app/services/canvas/students_processor.rb
- config/initializers/retrieve_canvas_students.rb
- spec/initializer/retrieve_canvas_students_spec.rb
Page the query to ensure that all users are pre-loaded
https://jira.ets.berkeley.edu/jira/browse/CYB-409
> CYB-409 - Engagement index: only 10 of 47 users appear on index initially

- app/controllers/api/v1/gallery_controller.rb
Fixed the likes and dislikes count for external URLs
https://jira.ets.berkeley.edu/jira/browse/CYB-393
> CYB-393 - Gallery: website URLs can receive negative likes and dislikes

- app/assets/javascripts/angular/factories/userFactory.js
Made the UI aware of the third possible admin role
https://jira.ets.berkeley.edu/jira/browse/CYB-423
> CYB-423 - Adv Designer should have same rights as Teacher

- app/assets/javascripts/angular/controllers/engagementIndexController.js
- app/assets/templates/engagement_index.html
- app/assets/templates/engagement_index_sharing_option.html
Allow Instructors to share engagement index points
https://jira.ets.berkeley.edu/jira/browse/CYB-427
> CYB-427 - Allow Instructors to share engagement index points

- app/assets/stylesheets/_main.scss
- app/assets/templates/points_configuration.html
Fixed critical issue coming out of the accessibility review
https://jira.ets.berkeley.edu/jira/browse/CYB-120
> CYB-120 - Accessibility Review

- app/assets/javascripts/angular/controllers/engagementIndexController.js
- app/assets/javascripts/angular/controllers/galleryCommentController.js
- app/assets/javascripts/angular/controllers/galleryController.js
- app/assets/javascripts/angular/controllers/galleryItemController.js
- app/assets/javascripts/angular/controllers/galleryLikeController.js
- app/assets/javascripts/angular/controllers/pointsConfigurationController.js
- app/assets/javascripts/angular/factories/engagementIndexFactory.js
- app/assets/javascripts/angular/services/analyticsService.js
- app/assets/javascripts/angular/services/galleryService.js
- app/assets/javascripts/angular/services/userService.js
- app/assets/templates/engagement_index_list.html
- app/assets/templates/gallery_item.html
- app/assets/templates/gallery_list.html
- app/views/layouts/application.html.erb
- config/.env_conf.yml.example
Implement MixPanel analytics
https://jira.ets.berkeley.edu/jira/browse/CYB-431
> CYB-431 - Implement MixPanel analytics

- app/assets/javascripts/angular/factories/galleryFactory.js
- app/services/canvas/submissions_processor.rb
- Ensure that the processor doesn't trip when an invalid Canvas response comes in
- Filter out non-image image submissions
https://jira.ets.berkeley.edu/jira/browse/CYB-432
> CYB-432 - Investigate invalid database record issue

- app/assets/javascripts/angular/controllers/galleryController.js
- app/assets/javascripts/angular/services/galleryService.js
Ensure that the "Load Gallery Tool" tracking event correctly tracks the associated user.
https://jira.ets.berkeley.edu/jira/browse/CYB-435
> CYB-435 - "Load Gallery Tool" doesn't track user correctly

- app/controllers/activities_controller.rb
Engagement index: activity export file no longer has .csv extension
https://jira.ets.berkeley.edu/jira/browse/CYB-436
> CYB-437 - Engagement index: activity export file no longer has .csv extension

- app/assets/javascripts/angular/controllers/engagementIndexController.js
The following JavaScript error shows when loading the Engagement Index as an administrator:
```
uncaught exception: Highcharts error #13: www.highcharts.com/errors/13
```
https://jira.ets.berkeley.edu/jira/browse/CYB-443
> CYB-443 - JavaScript error when loading Engagement Index as Instructor

- app/assets/javascripts/angular/controllers/engagementIndexController.js
Boxplot is no longer showing right whisker
https://jira.ets.berkeley.edu/jira/browse/CYB-444
> CYB-444 - Boxplot is no longer showing right whisker

- Gemfile
- Gemfile.lock
- app/assets/javascripts/angular/configuration/analyticsConfiguration.js
- app/assets/javascripts/angular/datacultures.js
- app/assets/javascripts/angular/services/analyticsService.js
- app/assets/javascripts/application.js
- app/views/layouts/application.html.erb
CYB-440: MixPanel is not recording all events
https://jira.ets.berkeley.edu/jira/browse/CYB-440
CYB-442:Data Cultures doesn't work without analytics configuration
https://jira.ets.berkeley.edu/jira/browse/CYB-442
> CYB-440 - MixPanel is not recording all events

- db/migrate/20150210112930_convert_url_image_url_to_text.rb
- db/schema.rb
Data Cultures can't deal with URLs longer than 255 characters
https://jira.ets.berkeley.edu/jira/browse/CYB-445
> CYB-445 - Data Cultures can't deal with URLs longer than 255 characters

- app/controllers/activities_controller.rb
Proposed fix for:
CSV: time stamp is in the wrong time zone
https://jira.ets.berkeley.edu/jira/browse/CYB-383
> CYB-383 - Outputting timestamps in the engagement index in the PST timezone

- lib/string_refinement.rb
Data Cultures not processing all YouTube URLs
https://jira.ets.berkeley.edu/jira/browse/CYB-448
> CYB-448 - Data Cultures not processing all YouTube URLs

- app/assets/javascripts/angular/controllers/engagementIndexController.js
- app/assets/javascripts/angular/controllers/galleryCommentController.js
- app/assets/javascripts/angular/controllers/galleryController.js
- app/assets/javascripts/angular/controllers/galleryItemController.js
- app/assets/javascripts/angular/controllers/pointsConfigurationController.js
- app/assets/javascripts/angular/services/utilService.js
LTI frame scrolling causes problems on slow connections
https://jira.ets.berkeley.edu/jira/browse/CYB-451
> CYB-451 - LTI frame scrolling causes problems on slow connections

- bin/deploy.sh
https://jira.ets.berkeley.edu/jira/browse/CYB-439
Per Darlene's attachment to Jira above.
> CYB-439, apply Darlene's work to fix: deploy.sh not writing sidekiq pid

- scripts/start_clockworkd.sh
Clockwork no longer starts successfully
https://jira.ets.berkeley.edu/jira/browse/CYB-454
> CYB-454 - Clockwork no longer starts successfully

- scripts/start_sidekiq.sh
Duplicate thumbnails
https://jira.ets.berkeley.edu/jira/browse/CYB-457
> CYB-457 - Duplicate thumbnails

- bin/deploy.sh
Duplicate thumbnails
https://jira.ets.berkeley.edu/jira/browse/CYB-464
> CYB-464 - Duplicate thumbnails

- .scss-lint.yml
Updated SCSS lint configuration
> Updated SCSS lint configuration

- app/assets/javascripts/angular/controllers/engagementIndexController.js
- app/services/canvas/discussion_entries_processor.rb
```
2015-03-26T16:52:55.357Z 31157 TID-13s8m8 WARN: {"retry"=>true, "queue"=>"default", "class"=>"DiscussionUpdateWorker", "args"=>["https://cole2.uconline.edu/", "317592"], "jid"=>"1a85273dc687ed75ad24cb74", "enqueued_at"=>1426721200.1744304, "error_message"=>"undefined method `each' for \"\":String", "error_class"=>"NoMethodError", "failed_at"=>1427388775.3558698, "retry_count"=>0}
2015-03-26T16:52:55.357Z 31157 TID-13s8m8 WARN: undefined method `each' for "":String
2015-03-26T16:52:55.357Z 31157 TID-13s8m8 WARN: /home/app_calcentral/datacultures/app/services/canvas/discussion_entries_processor.rb:16:in `call'
/home/app_calcentral/datacultures/app/services/canvas/paged_api_processor.rb:23:in `call'
/home/app_calcentral/datacultures/app/services/canvas/discussion_topics_processor.rb:58:in …
```
> Prevent processor from getting stuck
